ts-factory/bublik

- bublik/core/importruns/live/context.py
- bublik/core/importruns/source/execution.py
- bublik/core/run/objects.py
Fix issue #22 by fix blank test iteration result objects processing:
1. Do not create unnecessary blank objects
2. Use a special tin for blank objects
3. Update blank objects instead of creating duplicates
4. Add the ability to search and delete blank objects
> Fix strange percentages in run statistics

- bublik/core/run/stats.py
- bublik/interfaces/api_v2/__init__.py
- bublik/interfaces/api_v2/management.py
- bublik/interfaces/celery/tasks.py
- bublik/urls.py
Fix issue #20 by fix detailed stats calculation:
1. Fix the calculation of NOK iteration results number
2. Add the ability to drop detailed stats from cache for all runs
3. Calculate detailed stats only if they are not in the cache
> Fix negative values in detailed run stats

- bublik/core/report/components.py
- bublik/core/report/services.py
- bublik/interfaces/api_v2/__init__.py
- bublik/interfaces/api_v2/report.py
- bublik/urls.py
- templates/settings.py.template
`ReportViewSet`  have been created. It allows you to build run reports by passed configuration and get a list of run appropriate configurations.
Configuration JSON file must include:
- `id`,
- `name`,
- `description`,
- `version`,
- `title_content` (metadata list that will be used in the title),
- `test_names_order` (test names list for tests sorting),
- `tests` (test configurations list).
Test configuration must include:
- `table_view` (flag),
- `chart_view` (flag),
- `axis_x` (test argument),
- `axis_y` (measurement type with a list of measurement names (if you want specific ones) or with an empty list),
- `sequence_group_arg` (test argument that will be used to group the measurement results in a sequences),
- `percentage_base_value` (sequence group argument value, relative to which the …
> Add the ability to build run reports

- bublik/core/hash_system.py
- bublik/data/models/__init__.py
- bublik/data/models/endpoint_url.py
- bublik/data/serializers/__init__.py
- bublik/data/serializers/endpoint_url.py
- bublik/interfaces/api_v2/__init__.py
- bublik/interfaces/api_v2/url_shortener.py
- bublik/interfaces/main_api/__init__.py
- bublik/interfaces/main_api/redirects.py
- bublik/urls.py
1. The `HashedModelSerializer` has been changed to be able to serialize model objects, not all fields of which are hashable.
2. `EndpointURL` model, the corresponding serializer `EndpointURLSerializer` and `URLShortnerView` have been created. It allows you to create short URLs by replacing the endpoint of passed Bublik URL with its hash. All created hashes are stored in the database along with the corresponding views and endpoints to be able to redirect short URLs. The time of creation of the short URL is also stored in the database.
Bublik URL:
`http://localhost/bublik/v2/history?mode=linear&page=1&results=PASSED%3BFAILED%3BKILLED%3BCORED%3BSKIPPED%3BFAKED%3BINCOMPLETE&verdictLookup=string&startDate=2023-12-07&finishDate=2024-03-10&testName=promiscuous_mode&runProperties=notcompromised&pa …
> Add URL shortner

- scripts/deploy
We have no strict requirements on postgresql version in fact. Various versions work fine. Avoid version specification in deploy scripts to make it unnecessary to update the script on distro version update.
> Deploy: make deploy more flexible

- bublik/core/mail.py
- bublik/core/report/services.py
- bublik/interfaces/api_v2/auth.py
- bublik/interfaces/api_v2/server.py
- bublik/interfaces/management/commands/add_tags.py
Importing settings from django.conf is preferable because django.conf contains a more complete set of settings, including both project settings and Django settings.
> Settings: fix import of settings

- bublik/core/report/components.py
- bublik/core/report/services.py
- bublik/interfaces/api_v2/report.py
- doc/wiki/report_config.json
- doc/wiki/reports.md
- templates/settings.py.template
1. Fix empty percentage base value and invalid iterations handling
2. Expand possibilities of measurement setting by changing the report config structure
3. Update the report content structure to avoid duplication of common data
4. Ensure the uniqueness of IDs throughout the report
> Report: update and fix

- bublik/core/config/filters.py
- bublik/core/config/services.py
- bublik/core/mail.py
- bublik/core/report/services.py
- bublik/core/run/data.py
- bublik/core/run/metadata.py
- bublik/core/run/objects.py
- bublik/core/run/stats.py
- bublik/data/managers/result.py
- bublik/data/models/__init__.py
- bublik/data/models/config.py
- bublik/data/models/result.py
- bublik/data/schemas/per_conf.json
- bublik/data/schemas/report.json
- bublik/data/schemas/services.py
- bublik/data/serializers/__init__.py
- bublik/data/serializers/config.py
- bublik/interfaces/api_v2/__init__.py
- bublik/interfaces/api_v2/config.py
- bublik/interfaces/api_v2/dashboard.py
- bublik/interfaces/api_v2/performance.py
- bublik/interfaces/api_v2/report.py
- bublik/interfaces/api_v2/server.py
- bublik/interfaces/management/commands/importruns.py
- bublik/urls.py
- requirements.txt
- templates/settings.py.template
1. `Config` model, the corresponding serializer `ConfigSerializer` and `ConfigViewSet` have been created. This makes it possible to store configurations in the database, as well as manage them (CRUD).
2. The source of `per_conf` attributes and report configurations getting has been changed. Now this data is obtained from the corresponding database configuration objects.
`Config` model contains  configuration information.
Fields:
- `created` (timestamp of the config creation);
- `type` (configuration type. All available types are contained in the `ConfigTypes` class);
- `name` (configuration name. The namespace for global configurations is limited. All available global configuration names are contained in the `GlobalConfigNames` class);
- `version` (configuration version);
- `is_current` …
> Add configs management

- bublik/core/importruns/source/execution.py
- bublik/core/run/objects.py
- bublik/core/run/stats.py
- bublik/data/models/meta.py
- scripts/xml_log_parser
1. Store objectives in the database during import.
2. Add objectives to detailed run statistics.
> Run stats: add objectives support

- bublik/core/report/components.py
- bublik/core/report/services.py
- bublik/interfaces/api_v2/report.py
1. Cleanup.
2. Fix filtering by measurements and display of sequence group argument of not processed points.
3. Make displayed error messages, y-axis label, table header, not processed points data and report structure more informative.
4. Make report config more flexible (add the possibility of partial filtering by test name).
> Report: cleanup, bugfix and improve usability

- bublik/core/auth.py
- bublik/core/run/stats.py
- bublik/data/models/__init__.py
- bublik/data/models/meta.py
- bublik/data/models/result.py
- bublik/data/serializers/__init__.py
- bublik/data/serializers/result.py
- bublik/interfaces/api_v2/__init__.py
- bublik/interfaces/api_v2/comments.py
- bublik/interfaces/api_v2/results.py
- bublik/urls.py
1. `MetaTest` model, the corresponding serializer `MetaTestSerializer` and `TestCommentViewSet` have been created. This makes it possible to create, read, update and delete test comments.
2. The `check_action_permission()` function has been created. It allows you to grant access to some actions, by default available only to administrators, to all users.
3. The `get_run_stats_detailed_with_comments()` function has been created. It allows you to get detailed run statistics with comments on the tests.
`MetaTest` model contains information about the relationships between `Test` and `Meta` objects.
Fields:
- `updated` (timestamp of the object creation);
- `test`;
- `meta`;
- `serial` (serial number. Used to sort comments).
Methods:
- `delete()` method. Redefined so that after deleting an …
> Add test comments management

- bublik/interfaces/api_v2/report.py
The iteration may not have an argument, corresponding to the sequence group agrument from the report configuration, and, accordingly, it may not have its value.
> Report: fix not processed points handling

- bublik/core/run/filter_expression.py
Replace the outdated function, which is not supported in new versions of the pyparsing module, with a supported equivalent.
> History: fix filtering by expressions

- scripts/xml_log_parser
Since testing can take longer than one day, when calculating the start date of an iteration, it is necessary to use the ts_val of the latest message instead of the date of the first one, and also calculate the end date of the iteration using its duration.
> Importruns: fix iteration date parsing

- bublik/core/measurement/representation.py
Do not display empty brackets in the measurement chart label if there are no measurement keys.
> Report: fix measurement chart label

- bublik/data/models/config.py
- bublik/interfaces/api_v2/config.py
- bublik/interfaces/api_v2/report.py
Note the changes in the behavior of some endpoints:
This endpoint is no longer supported. Use `PATCH api/v2/config/<ID> Body: {'is_active': <updated status value>}` instead to update the status.
Now the PATCH method allows you to update the name and status as well.
Let's consider the case of a conflict between a passed and an already existing name.
Request data: 
```
{
"name": "DPDK Performance"
}
```
Responce data:
```
{
"type": "ValueError",
"message": "A report configuration with the same name already exist",
"new_config_data": {
"type": "report",
"name": "DPDK Performance",
"description": "Full performance report",
"content": {
"title_content": [
"CAMPAIGN_DATE",
"CFG"
],
"test_names_order": [
"testpmd_rxonly"
],
"tests": {
"testpmd_rxonly": {
"table_view": true,
"chart_view": true, …
```
> Config: bugfix, refactor and update

- bublik/core/run/external_links.py
Since the state of the references may be different, it is necessary to take into account the presence of a slash when source URL is built to avoid double splash and also use a join instead of os.path.join(), since it removes the previous items if the item starts with a slash.
> Urls: fix run source link building

- bublik/core/report/services.py
- bublik/interfaces/api_v2/report.py
1. Fix getting the applicable configs.
2. Change the data for report building.
Request: `GET api/v2/report/25/?config=<config ID>`
Responce data (updated): 
```
{
"warnings": [],
"config": {
"name": "Config name",
"version": 0,
"description": "Config description"
},
"content": [ ... ],
"unprocessed_iters": [ ... ]
}
```
Responce status code: 200
> Report: bugfix and update

- scripts/xml_log_parser
Fix the calculation of the start and end dates of the iteration when parsing logs.
> Importruns: fix log parsing

- bublik/core/auth.py
- bublik/interfaces/main_api/redirects.py
- bublik/interfaces/management/commands/reformat_configs.py
- bublik/middleware.py
- templates/settings.py.template
1. Create a middleware to get the values of Django dynamic settings from the active main configuration from the database, and not from the *per_conf.py*. Fix this in auth as well.
2. Add step to reformat the main configuration to ensure all `CSRF_TRUSTED_ORIGINS` use HTTP/HTTPS schemes if missing, as required by Django 4.0+.
> Settings, auth: update the source of the main configuration

- bublik/interfaces/api_v2/config.py
- bublik/urls.py
- requirements.txt
- templates/settings.py.template
This PR introduces DRF Spectacular to generate OpenAPI documentation for our API and integrates Swagger UI and Redoc as interactive documentation tools.  
This is an initial step toward comprehensive API documentation.
With this integration, clients will now be able to generate code in various programming languages to interact with the API, leveraging the OpenAPI schema.
- Added **DRF Spectacular** for OpenAPI schema generation.
- Configured **Swagger UI** and **Redoc** for visualising and exploring the API.
- Integrated schema URLs:
- Swagger: `/schema/swagger-ui/`
- Redoc: `/schema/redoc/`
- Schema: `/schema/swagger.yaml`
- Adjusted viewsets to ensure schema generation works without errors (e.g., adding queryset handling and filter overrides for unsupported fields like `JSONField`).
- …
> Add DRF Spectacular with Swagger and Redoc for API Documentation

- bublik/core/importruns/milog.py
- bublik/core/measurement/representation.py
- bublik/core/measurement/services.py
- bublik/core/report/components.py
- bublik/core/report/services.py
- bublik/data/models/__init__.py
- bublik/data/models/measurement.py
- bublik/data/serializers/__init__.py
- bublik/data/serializers/measurement.py
- bublik/interfaces/api_v2/measurements.py
- bublik/interfaces/api_v2/report.py
- bublik/interfaces/api_v2/results.py
- bublik/interfaces/management/commands/cleanup_db.py
1. Fixed duplication of `ChartView` objects during forced import.
2. Fixed creation of `ChartView` objects that are not linked to measurements.
3. Fixed creation of `ChartView` objects of types that do not correspond to the measurements. Now `X` and `Y` type `ChartView` objects are created only for measurements whose results are sequences, and `P` type `ChartView` objects are created only for measurements whose results are singles (for example, aggregations).
4. The sequences of measurement results (entries that differ from each other only in value) are saved as a list in a separate table (see `MeasurementResultList` below).
1. Fixed measurement chart labels.
2. Simplified grouping of points.
3. A little cleaning and refactoring has been done.
`MeasurementResultList` model has been …
> Update the import, storage and representation of measurement results

- bublik/interfaces/management/commands/cleanup_db.py
Use batch_size in bulk_create() to split the operation into smaller batches and prevent issues with large inserts.
> Management: fix mmr sequences migration

- bublik/core/measurement/representation.py
Consider all series for x-axis values, as the longest may miss points present in others.
> Report: fix x-axis value retrieval

- bublik/data/serializers/measurement.py
As a result of changes in the measurement results processing mechanism, the order of processing entries was modified, which in turn affects the serial number assigned to the measurement result. Therefore, during forced import, the same results may have different serial numbers and be treated as distinct, leading to object duplication. To prevent this, the serial number must be excluded from the check for measurement result existence in the database. This is correct because measurement result series are now stored as separate objects, and seriality of MeasurementResult objects is no longer supported.
Issue: #109
> Importruns: fix measurement results processing

- bublik/middleware.py
If the configuration object is missing, set default values when configuring dynamic settings.
> Settings: fix dynamic settings retrieval

- bublik/data/schemas/per_conf.json
- bublik/middleware.py
- templates/settings.py.template
Increase the flexibility of the email configuration by allowing the specification and modification of the EMAIL_PORT, EMAIL_HOST, EMAIL_USE_TLS, EMAIL_TIMEOUT, EMAIL_FROM, and EMAIL_ADMINS settings in the project configuration.
Issue: #116
> Settings: enhance email configuration flexibility

- bublik/core/report/components.py
Include the result type in each point's metadata to allow its representation in the report.
Issue: #108
> Report: enhance point metadata with result type

- bublik/data/schemas/per_conf.json
- bublik/middleware.py
If the configuration object is missing, set the default values from the corresponding schema when configuring the settings.
> Middleware: fix the retrieval of dynamic settings

- bublik/core/run/compromised.py
- bublik/core/run/keys.py
- bublik/core/run/stats.py
- bublik/interfaces/api_v2/outside_domains.py
The default value for issues should be an empty dictionary, as using None would result in an error when attempting to iterate.
> References: fix default value for issues

- bublik/interfaces/management/commands/migrate_configs.py
Make function name more accurate to reflect that it checks for any configuration files, not just non-empty ones.
> Management: make function name more accurate

- bublik/core/report/components.py
Include in the point metadata whether the result is expected, instead of the result type, as this will serve as the color indicator.
> Report: change chart points color indicator

- bublik/core/run/stats.py
It is required to modify the way the URI for issues is retrieved from the references configuration, as the URI value is now a string instead of a list of strings.
> Run stats: fix issue link building

- requirements.txt
Upgrade Django to version 5.1.7 and Cryptography to version 44.0.1.
> Requirements: update packages versions to pick up bug fixes

- bublik/core/cache.py
- bublik/core/run/stats.py
- bublik/interfaces/api_v2/results.py
1. Fix #138
2. Fix #156
3. Fix #155 
The new endpoint allows you to retrieve a list of all requirements found in the results of test run iterations.
Request: `GET /bublik/api/v2/runs/<run ID>/requirements/`
Response data:
```
{
"requirements": [
"FLOW_TRANSFER",
"GENEVE",
"I40E_UNSTABLE",
"NO_TEST_HARNESS_CHECKUP",
"OUTER_IP4",
"OUTER_IP6",
"RSS",
"RX_JUMBO",
"RX_SCATTER",
"TEREDO",
"TEST_HARNESS_CHECKUP",
"TSO",
"TSO_ENCAP",
"TX_MULTI_SEG",
"VLAN_INSERT",
"VXLAN"
]
}
```
Response status code: 200
> Run stats: add filtering by requirements and retrieving a list of all run requirements

- scripts/deploy
Add libkrb5-dev package which is required to build Python krb5.
> Deploy: fix requirements install

- scripts/deploy
Add 2to3 package which is required to build Python logilab-astng.
> Deploy: fix logilab-astng install

- bublik/interfaces/api_v2/event.py
Events should be sorted from newest to oldest, not the reverse.
> Event: fix event list sorting

- bublik/core/shortcuts.py
- bublik/interfaces/api_v2/url_shortener.py
1. Use raw string (prefix 'r') to prevent escape sequence interpretation.
2. Fix absolute URL and URL prefix construction
> URLs: fix URL construction and syntax warning

- bublik/interfaces/api_v2/importruns.py
Replace spaces with underscores in response data dictionary keys to ensure consistent access and avoid key lookup issues.
> Importruns: normalize response data dict keys

- bublik/middleware.py
Implement a signal to trigger meta categorization upon saving an active meta or tags configuration.
> Middleware: auto-categorize metas on config update

- bublik/core/measurement/services.py
- bublik/interfaces/api_v2/measurements.py
- bublik/interfaces/api_v2/results.py
Added API for per-result measurement series to enable stacked chart rendering in the UI.
Related to #113 
Trend chart data is now available via request `GET /bublik/api/v2/measurements/trend_charts/` instead of request `GET /bublik/api/v2/measurements/by_result_ids/`.
Request `GET /bublik/api/v2/measurements/by_result_ids/` can be used to retrieve data for per-result measurement series charts:
```
[
{
"run_id": 1,
"result_id": 336,
"start": "2025-05-31T05:49:21.675000Z",
"test_name": "ws_one_thread",
"parameters_list": [
"env=VAR.env.peer2peer",
"latency_interval=1",
"profile=none",
"send_rate=1000",
"send_size=300"
],
"measurement_series_charts": [
{
"id": "336_858",
"title": "rtt, ns",
"subtitle": "Latency (seconds, single): based on trade_server",
"axis_x": {
"label": "time (seconds)", …
```
> History: extend trend charts view data with measurement series chart

- bublik/core/history/v2/utils.py
- bublik/core/importruns/milog.py
- bublik/core/importruns/source/execution.py
- bublik/core/importruns/telog.py
- bublik/core/run/objects.py
- bublik/core/run/stats.py
- bublik/interfaces/management/commands/importruns.py
- scripts/xml_log_parser
Update XML log parser to generate logs in the new JSON format and adjust JSON log processing accordingly to support the updated structure. Import the run log in JSON format if the corresponding *bublik.json* file is present.
Extend data structure for multiple expected results and ensure naming consistency.
Changes in the response data structure must be considered for the following requests:
- `GET /bublik/api/v2/results/?parent_id=<parent ID\>&test_name=<test name\>`
- `GET /bublik/api/v2/history/?test_name=<test name\>`
Before:
```
"obtained_result": {
"result_type": "PASSED",
"verdict": []
},
"expected_result": {
"result_type": "PASSED",
"verdict": [],
"key": []
},
```
After:
```
"obtained_result": {
"result_type": "PASSED",
"verdicts": []
},
"expected_results": [
{
"result_type": …
```
> Update the run log and results JSON structures

- bublik/core/importruns/source/execution.py
Ensure test run is linked to project on reimport to prevent missing associations.
> Importurns: fix missing project link on reimport

- bublik/interfaces/api_v2/auth.py
`RefreshTokenView` was attempting to decode and validate a newly
generated access token immediately after deriving it from the refresh
token. Since this access token was not yet persisted and blacklisting
checks rely on existing claims, validation always failed, resulting in
`Not Authenticated` message
Changes:
- Resolve user directly from the refresh token payload `user_id`
- Old refresh token is blacklisted
- New tokens are issued without unnecessary validation of not active
access token
> auth: resolve invalid refresh flow due to premature access token validation

- bublik/urls.py
Update the regular expression for short URL redirect to allow project names consisting of multiple path segments.
> URLs: fix short URLs to work with multi-segment project names

- bublik/interfaces/api_v2/history.py
Remove spaces around keys and values when parsing parameter string to ensure correct filtering.
> History: fix filtering by parameters

- bublik/core/importruns/live/context.py
- bublik/core/importruns/source/execution.py
- bublik/core/run/metadata.py
- bublik/interfaces/management/commands/importruns.py
Done:
1. Prevent import failures when logs are missing
2. Prevent import failures when tags are missing
3. Link runs to projects in live import to fix errors in displaying running sessions and to prevent sessions from being unassociated with a project
4. Include metadata validation error messages in error events
> Importruns: bugfix

- bublik/core/meta/categorization.py
- bublik/core/run/stats.py
The response data now contains the configuration key:
```
{
"project_id": 1,
"project_name": "dpdk-ethdev-ts",
....
"special_categories": {
"Configuration": [
"galdor-x710-p0"
]
},
"configuration": "galdor-x710-p0"
}
```
Closes: #205
> Run data: add configuration to run details
