bublik/core/history/v1/utils.py, bublik/core/history/v2/utils.py, bublik/core/importruns/live/plan_tracking.py, bublik/core/importruns/milog.py, bublik/core/importruns/source/execution.py, bublik/core/mail.py, bublik/data/serializers/auth.py, bublik/interfaces/api_v2/auth.py, bublik/interfaces/celery/tasks.py, scripts/deploy
1. Fix issues #2, #3, #5.
2. Make deploy script a bit more convenient for development.
3. Take into account new import log format. 
4. Unify auth response data.
=> Fix various minor issues in v0.2.1

bublik/interfaces/celery/tasks.py, bublik/interfaces/management/commands/meta_categorization.py
=> Fix meta categorization

bublik/interfaces/api_v2/__init__.py, bublik/interfaces/api_v2/performance.py, bublik/urls.py, templates/settings.py.template
PerformanceCheckView has been created. It allows to get labels, URLs and timeouts for 5 basic views:
1. Dashboard
2. Runs List
3. Runs Charts
4. History List Base Filtering
5. History List Intense Filtering
The settings template has been updated with timeouts for all of them.
Request: `GET /bublik/performance_check/`
Response data:
```
[
{
"label": "Dashboard",
"url": "http://localhost/bublik/v2/dashboard/",
"timeout": 10
},
{
"label": "Runs List",
"url": "http://localhost/bublik/v2/runs/",
"timeout": 5
},
{
"label": "Runs Charts",
"url": "http://localhost/bublik/v2/runs?mode=charts",
"timeout": 300
},
{
"label": "History List Base Filtering",
"url": "http://localhost/bublik/v2/history/?testName=one_packet_ip4_seg&startDate=2023-01-01&finishDate=2024-01-01&runProperties=notcompromised&resu …
```
=> Performance check

bublik/core/run/objects.py
=> Fix update during importruns error

bublik/core/report/services.py, doc/wiki/report_config.json, doc/wiki/reports.md
1. Rename run report config dir
2. Update doc/wiki with run report config info
=> Run reports: addition and cleanup

bublik/core/report/components.py, bublik/core/report/services.py, bublik/core/utils.py
1. Make report configs and charts building more flexible
2. Add chart points sorting 
4. Make measurement units more readable
5. Cleanup
=> Report: fix bugs, take into account edits

bublik/core/run/stats.py, bublik/data/models/result.py, bublik/interfaces/api_v2/dashboard.py
1. Return the reason for the conclusion to make it clearer
2. Fix issue #3
=> Run stats: update and bugfix

bublik/data/models/endpoint_url.py
=> URLs: fix short URL creation

bublik/interfaces/management/commands/importruns.py
=> Importruns: discard more variants of parent directory refs

scripts/runflower
Ensure that celery is up and running before flower start
=> Flower: fix no workers in flower after start

bublik/core/auth.py, bublik/interfaces/api_v2/auth.py
1. Create and move functions to remove code duplication and improve readability
2. Unify authentication and admin verification
=> Auth: refactoring

bublik/core/auth.py, bublik/core/run/stats.py, bublik/data/models/meta.py, bublik/data/models/result.py, bublik/data/serializers/meta.py, bublik/data/serializers/result.py, bublik/interfaces/api_v2/results.py, bublik/urls.py
1. Formatting of the code using a linter.
2. Add "objective" to the list of possible values in the help text of the Meta model type field.
=> Cleanup and minor fix

bublik/data/schemas/per_conf.json, templates/settings.py.template
1. Fix the main config JSON schema to handle UI_VERSION 
2. Fix the source of getting the main config properties in settings.py
3. Add an email configuration option
=> Config: bugfix and make email settings more flexible

bublik/data/serializers/config.py, bublik/interfaces/api_v2/config.py
Fix the handling of unsupported attributes in the configuration.
=> Configs: refactor and fix

bublik/interfaces/api_v2/report.py
Import the missing function and add the missing argument to its call.
=> Report: fix unprocessed iters handling

bublik/core/measurement/representation.py, bublik/core/report/components.py, bublik/core/report/services.py, bublik/data/schemas/per_conf.json, bublik/data/schemas/report.json, bublik/data/serializers/config.py, bublik/interfaces/api_v2/config.py, bublik/interfaces/api_v2/dashboard.py, bublik/interfaces/management/commands/reformat_configs.py, templates/settings.py.template
1. Report: update record headers
2. Config: make it possible to reformat, update the main configuration migration, update the dashboard headers structure in the main configuration
3. Settings: increase the access token lifetime
=> Report, config, settings: update

bublik/core/measurement/representation.py, bublik/core/measurement/services.py, bublik/core/utils.py, bublik/data/models/measurement.py
Consider the multiplier in units of measurement, not in value.
=> Measurements: change the display of results

bublik/data/serializers/result.py
Replace the incorrect "leatest" with the correct "latest".
=> Cleanup: fix typo

bublik/core/importruns/source/execution.py, bublik/core/run/objects.py, bublik/core/run/stats.py, scripts/xml_log_parser
Add artifacts and requirements to result details.
=> Run stats: make result details more informative

requirements.txt
Upgrade the tornado version according to the Github Dependabot recommendations.
=> Requirements: fix the security issue

bublik/core/measurement/representation.py
Sort measurement results for display on the dynamics chart.
=> Measurements: fix dynamic chart points order

bublik/data/serializers/auth.py
Fix improper is_valid() usage.
=> Auth: fix password reset

bublik/core/measurement/representation.py
1. Align all sequences to the same x-axis by filling missing points with empty values.
2. Clean up using linter
=> Report: fix and clean up

bublik/core/measurement/representation.py, bublik/core/report/components.py, bublik/core/utils.py, bublik/data/models/measurement.py, bublik/interfaces/api_v2/measurements.py, bublik/interfaces/api_v2/report.py, bublik/interfaces/api_v2/results.py
1. Cleanup
2. Fix and update result merging by measurements
3. Fix measurement chart rendering without views
=> Measurements: bugfix and cleanup

bublik/interfaces/management/commands/cleanup_db.py
1. Fix creation of invalid MeasurementResultList objects during migration
2. Fix memory overload error during migration
=> Management: fix the database cleanup command

scripts/xml_log_parser
Fix parsing of objectives containing line breaks.
=> Importruns: fix objectives parsing

bublik/middleware.py
Since middleware runs on every request, the schema is loaded too frequently, slowing down page performance. To prevent this, the schema is cached and accessed only if the configuration or the required attribute is missing.
=> Middleware: improve performance

bublik/interfaces/management/commands/initialize_configs.py
Ensure a consistent output style by removing extra newline characters from configuration initialization.
=> Management: ensure consistent output style

bublik/core/measurement/representation.py
Enhance the dynamic chart points data with information on whether the result is as expected (fix #139).
=> Measurements: update dynamic charts points data

bublik/interfaces/api_v2/event.py
Sort the list of events with the newest ones first.
=> Event: sort the list of events

requirements.txt
Upgrade Gunicorn to version 23.0.0.
=> Requirements: update packages versions to pick up bug fixes

bublik/interfaces/api_v2/event.py
=> Event: optimize event list retrieval and enable event list sorting

bublik/interfaces/api_v2/log.py
=> Log: update response data with the artifacts URL

bublik/core/config/services.py, bublik/data/models/config.py, bublik/data/schemas/schedule.json, bublik/interfaces/api_v2/config.py
=> Config: add the schedule config type

README.md, scripts/deploy, templates/settings.py.template
Take into account the changes that were made to the layout in the dist directory some time ago.
=> Deploy: fix Bublik UI static location

bublik/interfaces/api_v2/event.py
Key changes include cleaner error messages and the inclusion of received and started import events in the event list.
1. Closes #130
2. Closes #131 
The response data for `GET /bublik/api/v2/session_import/` now includes events with statuses `RECEIVED` and `STARTED`. These new statuses may cause UI issues if not handled, so the UI needs to be updated accordingly.
=> Events: refactor list view, clean up messages, add received/started states

bublik/interfaces/api_v2/history.py
=> History: add the ability to filter by run IDs
